import "@/app/globals.css";
import localFont from "next/font/local";
import { StoreProvider } from "@/store/StoreProvider";
import Header from "@/components/custom/header";
import { ThemeProvider } from "@/components/custom/theme-provider";
import Footer from "@/components/custom/footer";

const myFont = localFont({
  src: "../font/Montserrat-VariableFont_wght.ttf",
  display: "swap",
});
export const metadata = {
  title: "Web Ban Do",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={myFont.className} suppressHydrationWarning>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            {children}
            <Footer />
          </ThemeProvider>
        </body>
      </html>
    </StoreProvider>
  );
}
